parameters:
    pomm_fos_user.user_map_class: Pomm\Bundle\FosUserBundle\Entity\UserMap

services:
    pomm_fos_user_bundle.user_map:
        class: %pomm_fos_user.user_map_class%
        arguments: ["@=service('pomm').getDatabase().getConnection()"]
    pomm_fos_user_bundle.user_manager:
        class: Pomm\Bundle\FosUserBundle\Model\UserManager
        arguments: [ @security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @pomm_fos_user_bundle.user_map ]
